# seed_indicators.py
# Auto-generates and inserts all FHSIS indicators into the database
# Run this script once to populate the indicators table
# Safe to run multiple times -- skips existing indicators

import sys
from pathlib import Path

import psycopg2

# Allow running this file directly (python backend/app/core/seed_indicators.py)
# as well as importing it via bootstrap_db.py — backend/ must be on sys.path
# for the `app.` package imports below.
sys.path.append(str(Path(__file__).resolve().parents[2]))

# Single source of truth for connection settings (no duplicated password
# fallback here — see app/core/db.py and app/core/env.py).
from app.core.db import get_db_config  # noqa: E402

# =====================================================
# INDICATOR DEFINITIONS
# Format per indicator:
# (code, name, unit, frequency_type, formula_type,
#  rate_multiplier, denominator_source, is_computed,
#  is_sensitive, target_value, target_year)
# =====================================================

INDICATORS = {

    # =================================================
    # CHILD CARE -- IMMUNIZATION
    # =================================================
    "CHILD_CARE": [

        # --- File 1: CPAB, BCG, HepaB ---
        # Population
        ("IMMUN_POP_0_11M", "Projected Population 0-11 Months",
         "count", "monthly", "count",
         100, None, False, False, None, None),

        # CPAB
        ("CPAB_MALE", "CPAB Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("CPAB_FEMALE", "CPAB Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("CPAB_TOTAL", "CPAB Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("CPAB_PCT", "CPAB Percentage",
         "percentage", "monthly", "percentage",
         100, "IMMUN_POP_0_11M", True, False, 0.95, 2026),

        # BCG within 24h
        ("BCG_24H_MALE", "BCG Within 24h Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("BCG_24H_FEMALE", "BCG Within 24h Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("BCG_24H_TOTAL", "BCG Within 24h Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("BCG_24H_PCT", "BCG Within 24h Percentage",
         "percentage", "monthly", "percentage",
         100, "IMMUN_POP_0_11M", True, False, None, None),

        # BCG >24h to 11m29d
        ("BCG_GT24H_MALE", "BCG >24h to 11m29d Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("BCG_GT24H_FEMALE", "BCG >24h to 11m29d Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("BCG_GT24H_TOTAL", "BCG >24h to 11m29d Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("BCG_GT24H_PCT", "BCG >24h to 11m29d Percentage",
         "percentage", "monthly", "percentage",
         100, "IMMUN_POP_0_11M", True, False, None, None),

        # HepaB within 24h
        ("HEPAB_24H_MALE", "HepaB Within 24h Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("HEPAB_24H_FEMALE", "HepaB Within 24h Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("HEPAB_24H_TOTAL", "HepaB Within 24h Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("HEPAB_24H_PCT", "HepaB Within 24h Percentage",
         "percentage", "monthly", "percentage",
         100, "IMMUN_POP_0_11M", True, False, None, None),

        # HepaB >24h to 14 days
        ("HEPAB_GT24H_MALE", "HepaB >24h to 14 Days Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("HEPAB_GT24H_FEMALE", "HepaB >24h to 14 Days Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("HEPAB_GT24H_TOTAL", "HepaB >24h to 14 Days Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("HEPAB_GT24H_PCT", "HepaB >24h to 14 Days Percentage",
         "percentage", "monthly", "percentage",
         100, "IMMUN_POP_0_11M", True, False, None, None),

        # --- File 4: DPT-HiB-HepB doses 1,2,3 ---
        # Current year population
        ("DPT_POP_2026", "DPT Projected Population 2026 (0-11 Months)",
         "count", "monthly", "count",
         100, None, False, False, None, None),

        # DPT dose 1 current year
        ("DPT1_MALE", "DPT-HiB-HepB Dose 1 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("DPT1_FEMALE", "DPT-HiB-HepB Dose 1 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("DPT1_TOTAL", "DPT-HiB-HepB Dose 1 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("DPT1_PCT", "DPT-HiB-HepB Dose 1 Percentage",
         "percentage", "monthly", "percentage",
         100, "DPT_POP_2026", True, False, None, None),

        # DPT dose 2 current year
        ("DPT2_MALE", "DPT-HiB-HepB Dose 2 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("DPT2_FEMALE", "DPT-HiB-HepB Dose 2 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("DPT2_TOTAL", "DPT-HiB-HepB Dose 2 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("DPT2_PCT", "DPT-HiB-HepB Dose 2 Percentage",
         "percentage", "monthly", "percentage",
         100, "DPT_POP_2026", True, False, None, None),

        # DPT dose 3 current year
        ("DPT3_MALE", "DPT-HiB-HepB Dose 3 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("DPT3_FEMALE", "DPT-HiB-HepB Dose 3 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("DPT3_TOTAL", "DPT-HiB-HepB Dose 3 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("DPT3_PCT", "DPT-HiB-HepB Dose 3 Percentage",
         "percentage", "monthly", "percentage",
         100, "DPT_POP_2026", True, False, None, None),

        # --- File 5: OPV doses 1,2,3 ---
        ("OPV_POP_2026", "OPV Projected Population 2026 (0-11 Months)",
         "count", "monthly", "count",
         100, None, False, False, None, None),

        ("OPV1_MALE", "OPV Dose 1 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("OPV1_FEMALE", "OPV Dose 1 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("OPV1_TOTAL", "OPV Dose 1 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("OPV1_PCT", "OPV Dose 1 Percentage",
         "percentage", "monthly", "percentage",
         100, "OPV_POP_2026", True, False, None, None),

        ("OPV2_MALE", "OPV Dose 2 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("OPV2_FEMALE", "OPV Dose 2 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("OPV2_TOTAL", "OPV Dose 2 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("OPV2_PCT", "OPV Dose 2 Percentage",
         "percentage", "monthly", "percentage",
         100, "OPV_POP_2026", True, False, None, None),

        ("OPV3_MALE", "OPV Dose 3 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("OPV3_FEMALE", "OPV Dose 3 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("OPV3_TOTAL", "OPV Dose 3 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("OPV3_PCT", "OPV Dose 3 Percentage",
         "percentage", "monthly", "percentage",
         100, "OPV_POP_2026", True, False, None, None),

        # --- File 6: IPV doses 1,2 ---
        ("IPV_POP_2026", "IPV Projected Population 2026 (0-11 Months)",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("IPV1_MALE", "IPV Dose 1 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("IPV1_FEMALE", "IPV Dose 1 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("IPV1_TOTAL", "IPV Dose 1 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("IPV1_PCT", "IPV Dose 1 Percentage",
         "percentage", "monthly", "percentage",
         100, "IPV_POP_2026", True, False, None, None),
        ("IPV2_MALE", "IPV Dose 2 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("IPV2_FEMALE", "IPV Dose 2 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("IPV2_TOTAL", "IPV Dose 2 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("IPV2_PCT", "IPV Dose 2 Percentage",
         "percentage", "monthly", "percentage",
         100, "IPV_POP_2026", True, False, None, None),

        # --- File 7: PCV doses 1,2,3 ---
        ("PCV_POP_2026", "PCV Projected Population 2026 (0-11 Months)",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("PCV1_MALE", "PCV Dose 1 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("PCV1_FEMALE", "PCV Dose 1 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("PCV1_TOTAL", "PCV Dose 1 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("PCV1_PCT", "PCV Dose 1 Percentage",
         "percentage", "monthly", "percentage",
         100, "PCV_POP_2026", True, False, None, None),
        ("PCV2_MALE", "PCV Dose 2 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("PCV2_FEMALE", "PCV Dose 2 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("PCV2_TOTAL", "PCV Dose 2 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("PCV2_PCT", "PCV Dose 2 Percentage",
         "percentage", "monthly", "percentage",
         100, "PCV_POP_2026", True, False, None, None),
        ("PCV3_MALE", "PCV Dose 3 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("PCV3_FEMALE", "PCV Dose 3 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("PCV3_TOTAL", "PCV Dose 3 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("PCV3_PCT", "PCV Dose 3 Percentage",
         "percentage", "monthly", "percentage",
         100, "PCV_POP_2026", True, False, None, None),

        # --- File 8: MMR 1/2 (FIC/CIC shared below) ---
        ("MMR_POP_2026", "MMR Projected Population 2026 (0-11 Months)",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("MMR1_MALE", "MMR Dose 1 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("MMR1_FEMALE", "MMR Dose 1 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("MMR1_TOTAL", "MMR Dose 1 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("MMR1_PCT", "MMR Dose 1 Percentage",
         "percentage", "monthly", "percentage",
         100, "MMR_POP_2026", True, False, None, None),
        ("MMR1_PREV_MALE", "MMR Dose 1 Male (Previous Year Cohort)",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("MMR1_PREV_FEMALE", "MMR Dose 1 Female (Previous Year Cohort)",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("MMR1_PREV_TOTAL", "MMR Dose 1 Total (Previous Year Cohort)",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("MMR1_PREV_PCT", "MMR Dose 1 Percentage (Previous Year Cohort)",
         "percentage", "monthly", "percentage",
         100, "IMMUN_POP_0_11M_PREV", True, False, None, None),
        ("MMR2_MALE", "MMR Dose 2 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("MMR2_FEMALE", "MMR Dose 2 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("MMR2_TOTAL", "MMR Dose 2 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("MMR2_PCT", "MMR Dose 2 Percentage",
         "percentage", "monthly", "percentage",
         100, "IMMUN_POP_0_11M_PREV", True, False, None, None),

        # --- Management of the Sick: Vitamin A ---
        ("SICK_VITA_SEEN_611_MALE", "Sick Seen 6-11m Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("SICK_VITA_SEEN_611_FEMALE", "Sick Seen 6-11m Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("SICK_VITA_SEEN_611_TOTAL", "Sick Seen 6-11m Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("SICK_VITA_GIVEN_611_MALE", "Sick 6-11m Given Vitamin A Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("SICK_VITA_GIVEN_611_FEMALE", "Sick 6-11m Given Vitamin A Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("SICK_VITA_GIVEN_611_TOTAL", "Sick 6-11m Given Vitamin A Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("SICK_VITA_GIVEN_611_PCT", "Sick 6-11m Given Vitamin A Percentage",
         "percentage", "quarterly", "percentage",
         100, "SICK_VITA_SEEN_611_TOTAL", True, False, None, None),
        ("SICK_VITA_SEEN_1259_MALE", "Sick Seen 12-59m Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("SICK_VITA_SEEN_1259_FEMALE", "Sick Seen 12-59m Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("SICK_VITA_SEEN_1259_TOTAL", "Sick Seen 12-59m Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("SICK_VITA_GIVEN_1259_MALE", "Sick 12-59m Given Vitamin A Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("SICK_VITA_GIVEN_1259_FEMALE", "Sick 12-59m Given Vitamin A Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("SICK_VITA_GIVEN_1259_TOTAL", "Sick 12-59m Given Vitamin A Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("SICK_VITA_GIVEN_1259_PCT", "Sick 12-59m Given Vitamin A Percentage",
         "percentage", "quarterly", "percentage",
         100, "SICK_VITA_SEEN_1259_TOTAL", True, False, None, None),

        # --- Management of the Sick: Diarrhea & Pneumonia ---
        ("DIAR_SEEN_MALE", "Diarrhea Cases Seen Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("DIAR_SEEN_FEMALE", "Diarrhea Cases Seen Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("DIAR_SEEN_TOTAL", "Diarrhea Cases Seen Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("DIAR_ORS_MALE", "Diarrhea Given ORS Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("DIAR_ORS_FEMALE", "Diarrhea Given ORS Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("DIAR_ORS_TOTAL", "Diarrhea Given ORS Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("DIAR_ORS_PCT", "Diarrhea Given ORS Percentage",
         "percentage", "quarterly", "percentage",
         100, "DIAR_SEEN_TOTAL", True, False, None, None),
        ("DIAR_ORSZ_MALE", "Diarrhea Given ORS+Zinc Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("DIAR_ORSZ_FEMALE", "Diarrhea Given ORS+Zinc Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("DIAR_ORSZ_TOTAL", "Diarrhea Given ORS+Zinc Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("DIAR_ORSZ_PCT", "Diarrhea Given ORS+Zinc Percentage",
         "percentage", "quarterly", "percentage",
         100, "DIAR_SEEN_TOTAL", True, False, None, None),
        ("DIAR_COMBINED_TOTAL", "Diarrhea Combined Treatment Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("DIAR_COMBINED_PCT", "Diarrhea Combined Treatment Percentage",
         "percentage", "quarterly", "percentage",
         100, "DIAR_SEEN_TOTAL", True, False, None, None),
        ("PNEU_SEEN_MALE", "Pneumonia Cases Seen Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("PNEU_SEEN_FEMALE", "Pneumonia Cases Seen Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("PNEU_SEEN_TOTAL", "Pneumonia Cases Seen Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("PNEU_ABX_MALE", "Pneumonia Given Antibiotic Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("PNEU_ABX_FEMALE", "Pneumonia Given Antibiotic Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("PNEU_ABX_TOTAL", "Pneumonia Given Antibiotic Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("PNEU_ABX_PCT", "Pneumonia Given Antibiotic Percentage",
         "percentage", "quarterly", "percentage",
         100, "PNEU_SEEN_TOTAL", True, False, None, None),

        # --- Nutrition: File 1 Breastfeeding and LBW ---
        ("NUT_BF_LIVE_BIRTHS", "Live Births",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_BF_1H_MALE", "Breastfeeding Within 1 Hour Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_BF_1H_FEMALE", "Breastfeeding Within 1 Hour Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_BF_1H_TOTAL", "Breastfeeding Within 1 Hour Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("NUT_BF_1H_PCT", "Breastfeeding Within 1 Hour Percentage",
         "percentage", "quarterly", "percentage",
         100, "NUT_BF_LIVE_BIRTHS", True, False, None, None),
        ("NUT_LBW_COUNT", "Low Birth Weight Count",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_LBW_IRON_MALE", "LBW Given Iron Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_LBW_IRON_FEMALE", "LBW Given Iron Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_LBW_IRON_TOTAL", "LBW Given Iron Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("NUT_LBW_IRON_PCT", "LBW Given Iron Percentage",
         "percentage", "quarterly", "percentage",
         100, "NUT_LBW_COUNT", True, False, None, None),

        # --- Nutrition: Files 2-3 Vitamin A ---
        ("NUT_VITA_POP_611", "Projected Population 6-11 Months (Vitamin A)",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_VITA_611_MALE", "Vitamin A 6-11m Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_VITA_611_FEMALE", "Vitamin A 6-11m Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_VITA_611_TOTAL", "Vitamin A 6-11m Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("NUT_VITA_611_PCT", "Vitamin A 6-11m Percentage",
         "percentage", "quarterly", "percentage",
         100, "NUT_VITA_POP_611", True, False, None, None),
        ("NUT_VITA_POP_1259", "Projected Population 12-59 Months (Vitamin A)",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_VITA_1259_MALE", "Vitamin A 12-59m Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_VITA_1259_FEMALE", "Vitamin A 12-59m Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_VITA_1259_TOTAL", "Vitamin A 12-59m Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("NUT_VITA_1259_PCT", "Vitamin A 12-59m Percentage",
         "percentage", "quarterly", "percentage",
         100, "NUT_VITA_POP_1259", True, False, None, None),

        # --- Nutrition: File 4 MNP ---
        ("NUT_MNP_POP_611", "Projected Population 6-11 Months (MNP)",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_MNP_611_MALE", "MNP 6-11m Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_MNP_611_FEMALE", "MNP 6-11m Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_MNP_611_TOTAL", "MNP 6-11m Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("NUT_MNP_611_PCT", "MNP 6-11m Percentage",
         "percentage", "quarterly", "percentage",
         100, "NUT_MNP_POP_611", True, False, None, None),
        ("NUT_MNP_POP_1223", "Projected Population 12-23 Months (MNP)",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_MNP_1223_MALE", "MNP 12-23m Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_MNP_1223_FEMALE", "MNP 12-23m Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_MNP_1223_TOTAL", "MNP 12-23m Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("NUT_MNP_1223_PCT", "MNP 12-23m Percentage",
         "percentage", "quarterly", "percentage",
         100, "NUT_MNP_POP_1223", True, False, None, None),

        # --- Nutrition: File 5 LNS-SQ ---
        ("NUT_LNS_POP_611", "Projected Population 6-11 Months (LNS-SQ)",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_LNS_611_MALE", "LNS-SQ 6-11m Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_LNS_611_FEMALE", "LNS-SQ 6-11m Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_LNS_611_TOTAL", "LNS-SQ 6-11m Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("NUT_LNS_611_PCT", "LNS-SQ 6-11m Percentage",
         "percentage", "quarterly", "percentage",
         100, "NUT_LNS_POP_611", True, False, None, None),
        ("NUT_LNS_POP_1223", "Projected Population 12-23 Months (LNS-SQ)",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_LNS_1223_MALE", "LNS-SQ 12-23m Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_LNS_1223_FEMALE", "LNS-SQ 12-23m Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_LNS_1223_TOTAL", "LNS-SQ 12-23m Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("NUT_LNS_1223_PCT", "LNS-SQ 12-23m Percentage",
         "percentage", "quarterly", "percentage",
         100, "NUT_LNS_POP_1223", True, False, None, None),

        # --- Nutrition: File 6 MAM & SAM (Annual) ---
        ("NUT_MAM_SEEN_MALE", "MAM Children Seen Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_SEEN_FEMALE", "MAM Children Seen Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_SEEN_TOTAL", "MAM Children Seen Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_MAM_ID_MALE", "MAM Identified Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_ID_FEMALE", "MAM Identified Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_ID_TOTAL", "MAM Identified Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_MAM_ID_PCT", "MAM Identified Percentage",
         "percentage", "annual", "percentage", 100, "NUT_MAM_SEEN_TOTAL", True, False, None, None),
        ("NUT_MAM_SFP_MALE", "MAM Enrolled SFP Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_SFP_FEMALE", "MAM Enrolled SFP Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_SFP_TOTAL", "MAM Enrolled SFP Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_MAM_SFP_PCT", "MAM Enrolled SFP Percentage",
         "percentage", "annual", "percentage", 100, "NUT_MAM_SEEN_TOTAL", True, False, None, None),
        ("NUT_MAM_CURED_MALE", "MAM Cured SFP Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_CURED_FEMALE", "MAM Cured SFP Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_CURED_TOTAL", "MAM Cured SFP Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_MAM_CURED_PCT", "MAM Cured SFP Percentage",
         "percentage", "annual", "percentage", 100, "NUT_MAM_SEEN_TOTAL", True, False, None, None),
        ("NUT_MAM_NONCURED_MALE", "MAM Non-cured SFP Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_NONCURED_FEMALE", "MAM Non-cured SFP Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_NONCURED_TOTAL", "MAM Non-cured SFP Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_MAM_NONCURED_PCT", "MAM Non-cured SFP Percentage",
         "percentage", "annual", "percentage", 100, "NUT_MAM_SEEN_TOTAL", True, False, None, None),
        ("NUT_MAM_DEFAULT_MALE", "MAM Defaulted SFP Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_DEFAULT_FEMALE", "MAM Defaulted SFP Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_DEFAULT_TOTAL", "MAM Defaulted SFP Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_MAM_DEFAULT_PCT", "MAM Defaulted SFP Percentage",
         "percentage", "annual", "percentage", 100, "NUT_MAM_SEEN_TOTAL", True, False, None, None),
        ("NUT_MAM_DIED_MALE", "MAM Died SFP Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_DIED_FEMALE", "MAM Died SFP Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_DIED_TOTAL", "MAM Died SFP Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_MAM_DIED_PCT", "MAM Died SFP Percentage",
         "percentage", "annual", "percentage", 100, "NUT_MAM_SEEN_TOTAL", True, False, None, None),
        ("NUT_SAM_SEEN_MALE", "SAM Children Seen Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_SEEN_FEMALE", "SAM Children Seen Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_SEEN_TOTAL", "SAM Children Seen Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_SAM_ID_MALE", "SAM Identified Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_ID_FEMALE", "SAM Identified Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_ID_TOTAL", "SAM Identified Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_SAM_ID_PCT", "SAM Identified Percentage",
         "percentage", "annual", "percentage", 100, "NUT_SAM_SEEN_TOTAL", True, False, None, None),
        ("NUT_SAM_OTC_MALE", "SAM Admitted OTC Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_OTC_FEMALE", "SAM Admitted OTC Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_OTC_TOTAL", "SAM Admitted OTC Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_SAM_OTC_PCT", "SAM Admitted OTC Percentage",
         "percentage", "annual", "percentage", 100, "NUT_SAM_SEEN_TOTAL", True, False, None, None),
        ("NUT_SAM_CURED_MALE", "SAM Cured OTC Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_CURED_FEMALE", "SAM Cured OTC Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_CURED_TOTAL", "SAM Cured OTC Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_SAM_CURED_PCT", "SAM Cured OTC Percentage",
         "percentage", "annual", "percentage", 100, "NUT_SAM_SEEN_TOTAL", True, False, None, None),
        ("NUT_SAM_NONCURED_MALE", "SAM Non-cured OTC Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_NONCURED_FEMALE", "SAM Non-cured OTC Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_NONCURED_TOTAL", "SAM Non-cured OTC Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_SAM_NONCURED_PCT", "SAM Non-cured OTC Percentage",
         "percentage", "annual", "percentage", 100, "NUT_SAM_SEEN_TOTAL", True, False, None, None),
        ("NUT_SAM_DEFAULT_MALE", "SAM Defaulted OTC Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_DEFAULT_FEMALE", "SAM Defaulted OTC Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_DEFAULT_TOTAL", "SAM Defaulted OTC Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_SAM_DEFAULT_PCT", "SAM Defaulted OTC Percentage",
         "percentage", "annual", "percentage", 100, "NUT_SAM_SEEN_TOTAL", True, False, None, None),
        ("NUT_SAM_DIED_MALE", "SAM Died OTC Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_DIED_FEMALE", "SAM Died OTC Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_DIED_TOTAL", "SAM Died OTC Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_SAM_DIED_PCT", "SAM Died OTC Percentage",
         "percentage", "annual", "percentage", 100, "NUT_SAM_SEEN_TOTAL", True, False, None, None),

        # FIC and CIC
        ("FIC_MALE", "Fully Immunized Child Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("FIC_FEMALE", "Fully Immunized Child Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("FIC_TOTAL", "Fully Immunized Child Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("FIC_PCT", "Fully Immunized Child Percentage",
         "percentage", "monthly", "percentage",
         100, "IMMUN_POP_0_11M_PREV", True, False, 0.95, 2026),

        ("CIC_MALE", "Completely Immunized Child Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("CIC_FEMALE", "Completely Immunized Child Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("CIC_TOTAL", "Completely Immunized Child Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("CIC_PCT", "Completely Immunized Child Percentage",
         "percentage", "monthly", "percentage",
         100, "PREV_POP_MINUS_FIC", True, False, 0.95, 2026),

        ("PREV_POP_MINUS_FIC",
         "Previous Year Population Minus FIC (CIC Denominator)",
         "count", "monthly", "count",
         100, None, True, False, None, None),

        # Previous year population (for MMR2, FIC, CIC)
        ("IMMUN_POP_0_11M_PREV",
         "Projected Population 0-11 Months Previous Year",
         "count", "monthly", "count",
         100, None, False, False, None, None),

        # =================================================
        # CHILD CARE -- SBI (School-Based Immunization), annual
        # Denominator = enrolled learners (a column in the file, from DepEd),
        # not the health population table.
        # =================================================

        # --- File 9: G1 & G7 given Td vaccine ---
        ("SBI_TD_G1_ENROLLED", "Td: Grade 1 Enrolled Learners",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_TD_G1_MALE", "Td: Grade 1 Given Td Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_TD_G1_FEMALE", "Td: Grade 1 Given Td Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_TD_G1_TOTAL", "Td: Grade 1 Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("SBI_TD_G1_PCT", "Td: Grade 1 Percentage",
         "percentage", "annual", "percentage",
         100, "SBI_TD_G1_ENROLLED", True, False, 0.95, 2026),
        ("SBI_TD_G7_ENROLLED", "Td: Grade 7 Enrolled Learners",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_TD_G7_MALE", "Td: Grade 7 Given Td Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_TD_G7_FEMALE", "Td: Grade 7 Given Td Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_TD_G7_TOTAL", "Td: Grade 7 Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("SBI_TD_G7_PCT", "Td: Grade 7 Percentage",
         "percentage", "annual", "percentage",
         100, "SBI_TD_G7_ENROLLED", True, False, 0.95, 2026),

        # --- File 10: G1 & G7 given MR vaccine (same shape as Td) ---
        ("SBI_MR_G1_ENROLLED", "MR: Grade 1 Enrolled Learners",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_MR_G1_MALE", "MR: Grade 1 Given MR Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_MR_G1_FEMALE", "MR: Grade 1 Given MR Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_MR_G1_TOTAL", "MR: Grade 1 Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("SBI_MR_G1_PCT", "MR: Grade 1 Percentage",
         "percentage", "annual", "percentage",
         100, "SBI_MR_G1_ENROLLED", True, False, 0.95, 2026),
        ("SBI_MR_G7_ENROLLED", "MR: Grade 7 Enrolled Learners",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_MR_G7_MALE", "MR: Grade 7 Given MR Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_MR_G7_FEMALE", "MR: Grade 7 Given MR Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_MR_G7_TOTAL", "MR: Grade 7 Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("SBI_MR_G7_PCT", "MR: Grade 7 Percentage",
         "percentage", "annual", "percentage",
         100, "SBI_MR_G7_ENROLLED", True, False, 0.95, 2026),

        # --- File 11: HPV (female-only; SBI + CBI delivery) ---
        ("HPV_G4_ENROLLED", "HPV: Grade 4 Female Enrolled (public + private)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("HPV1_SBI", "HPV1 via SBI (Grade 4 female, >=9 yrs)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("HPV1_SBI_PCT", "HPV1 SBI Percentage",
         "percentage", "annual", "percentage",
         100, "HPV_G4_ENROLLED", True, False, 0.95, 2026),
        ("HPV1_CBI", "HPV1 via CBI (9-year-old female)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("HPV1_COMBINED", "HPV1 Combined Total (SBI + CBI)",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("HPV2_CBI", "HPV2 via CBI",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("HPV2_PCT", "HPV2 Percentage (of HPV1 recipients)",
         "percentage", "annual", "percentage",
         100, "HPV1_COMBINED", True, False, 0.95, 2026),
    ],

    # =================================================
    # DEMOGRAPHICS -- facility & workforce density
    # (population-per-resource ratios, not coverage %)
    # =================================================
    "DEMOGRAPHICS": [

        # --- Sheet: BGY & BHS (facility density) ---
        ("DEMO_POP", "Projected Population",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_BGY_COUNT", "Number of Barangays",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_BGY_RATIO", "Population per Barangay",
         "ratio", "annual", "ratio", 100, "DEMO_BGY_COUNT", True, False, None, None),
        ("DEMO_MUNIHC_COUNT", "Number of Municipal Health Centers",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_MUNIHC_RATIO", "Population per Municipal Health Center",
         "ratio", "annual", "ratio", 100, "DEMO_MUNIHC_COUNT", True, False, None, None),
        ("DEMO_CITYHC_COUNT", "Number of City Health Centers",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_CITYHC_RATIO", "Population per City Health Center",
         "ratio", "annual", "ratio", 100, "DEMO_CITYHC_COUNT", True, False, None, None),
        ("DEMO_RURALHU_COUNT", "Number of Rural Health Units",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_RURALHU_RATIO", "Population per Rural Health Unit",
         "ratio", "annual", "ratio", 100, "DEMO_RURALHU_COUNT", True, False, None, None),
        ("DEMO_TOTALHC_COUNT", "Total Health Centers (Municipal + City + Rural)",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("DEMO_TOTALHC_RATIO", "Population per Health Center (Total)",
         "ratio", "annual", "ratio", 100, "DEMO_TOTALHC_COUNT", True, False, None, None),
        ("DEMO_BHS_COUNT", "Number of Barangay Health Stations (BHS)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_BHS_RATIO", "Population per Barangay Health Station",
         "ratio", "annual", "ratio", 100, "DEMO_BHS_COUNT", True, False, None, None),

        # --- Sheet: Health Workers (workforce density) ---
        ("DEMO_HOUSEHOLDS", "Projected Number of Households",
         "count", "annual", "count", 100, None, False, False, None, None),

        ("DEMO_DOCTORS_LGU", "Doctors (LGU Hired)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_DOCTORS_DOH", "Doctors (DOH Hired)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_DOCTORS_TOTAL", "Doctors (Total)",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("DEMO_DOCTORS_RATIO", "Population per Doctor",
         "ratio", "annual", "ratio", 100, "DEMO_DOCTORS_TOTAL", True, False, None, None),

        ("DEMO_NURSES_LGU", "Nurses (LGU Hired)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_NURSES_DOH", "Nurses (DOH Hired)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_NURSES_TOTAL", "Nurses (Total)",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("DEMO_NURSES_RATIO", "Population per Nurse",
         "ratio", "annual", "ratio", 100, "DEMO_NURSES_TOTAL", True, False, None, None),

        ("DEMO_MIDWIVES_LGU", "Midwives (LGU Hired)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_MIDWIVES_DOH", "Midwives (DOH Hired)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_MIDWIVES_TOTAL", "Midwives (Total)",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("DEMO_MIDWIVES_RATIO", "Population per Midwife",
         "ratio", "annual", "ratio", 100, "DEMO_MIDWIVES_TOTAL", True, False, None, None),

        ("DEMO_DENTISTS_LGU", "Dentists (LGU Hired)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_DENTISTS_DOH", "Dentists (DOH Hired)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_DENTISTS_TOTAL", "Dentists (Total)",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("DEMO_DENTISTS_RATIO", "Population per Dentist",
         "ratio", "annual", "ratio", 100, "DEMO_DENTISTS_TOTAL", True, False, None, None),

        ("DEMO_MEDTECH_LGU", "Medical Technologists (LGU Hired)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_MEDTECH_DOH", "Medical Technologists (DOH Hired)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_MEDTECH_TOTAL", "Medical Technologists (Total)",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("DEMO_MEDTECH_RATIO", "Population per Medical Technologist",
         "ratio", "annual", "ratio", 100, "DEMO_MEDTECH_TOTAL", True, False, None, None),

        ("DEMO_NUTRITIONISTS_LGU", "Nutritionists (LGU Hired)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_NUTRITIONISTS_DOH", "Nutritionists (DOH Hired)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_NUTRITIONISTS_TOTAL", "Nutritionists (Total)",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("DEMO_NUTRITIONISTS_RATIO", "Population per Nutritionist",
         "ratio", "annual", "ratio", 100, "DEMO_NUTRITIONISTS_TOTAL", True, False, None, None),

        ("DEMO_SANENGR_LGU", "Sanitary Engineers (LGU Hired)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_SANENGR_DOH", "Sanitary Engineers (DOH Hired)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_SANENGR_TOTAL", "Sanitary Engineers (Total)",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("DEMO_SANENGR_RATIO", "Population per Sanitary Engineer",
         "ratio", "annual", "ratio", 100, "DEMO_SANENGR_TOTAL", True, False, None, None),

        ("DEMO_SANINSP_LGU", "Sanitary Inspectors (LGU Hired)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_SANINSP_DOH", "Sanitary Inspectors (DOH Hired)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_SANINSP_TOTAL", "Sanitary Inspectors (Total)",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("DEMO_SANINSP_RATIO", "Population per Sanitary Inspector",
         "ratio", "annual", "ratio", 100, "DEMO_SANINSP_TOTAL", True, False, None, None),

        ("DEMO_BHW_LGU", "Active BHW (LGU Hired)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_BHW_DOH", "Active BHW (DOH Hired)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("DEMO_BHW_TOTAL", "Active BHW (Total)",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("DEMO_BHW_RATIO", "Households per Active BHW",
         "ratio", "annual", "ratio", 100, "DEMO_BHW_TOTAL", True, False, None, None),
    ],

    # =================================================
    # INFECTIOUS DISEASE -- antenatal HIV/Syphilis/HepaB screening
    # Region/2 provinces/Siquijor/Bacolod HUC only (5 rows), age-band
    # disaggregation (10-14/15-19/20-49), quarterly data entry.
    # Reactive + (Syphilis-only) treated columns are is_sensitive=True
    # per the 2026-07-09 sensitive-indicator policy expansion.
    # =================================================
    "INFECTIOUS_DISEASE": [

        # --- HIV (infec_hiv_nir.xlsx) ---
        ("HIV_POP_U1", "Projected Population Under 1 (HIV file)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("HIV_SCREEN_10_14", "Screened for HIV (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("HIV_SCREEN_15_19", "Screened for HIV (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("HIV_SCREEN_20_49", "Screened for HIV (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("HIV_SCREEN_TOTAL", "Screened for HIV Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("HIV_SCREEN_PCT", "Screened for HIV Percentage",
         "percentage", "quarterly", "percentage",
         100, "HIV_POP_U1", True, False, None, None),
        ("HIV_REACTIVE_10_14", "Reactive for HIV (10-14y)",
         "count", "quarterly", "count", 100, None, False, True, None, None),
        ("HIV_REACTIVE_15_19", "Reactive for HIV (15-19y)",
         "count", "quarterly", "count", 100, None, False, True, None, None),
        ("HIV_REACTIVE_20_49", "Reactive for HIV (20-49y)",
         "count", "quarterly", "count", 100, None, False, True, None, None),
        ("HIV_REACTIVE_TOTAL", "Reactive for HIV Total",
         "count", "quarterly", "sum", 100, None, True, True, None, None),
        ("HIV_REACTIVE_PCT", "Reactive for HIV Percentage (of screened)",
         "percentage", "quarterly", "percentage",
         100, "HIV_SCREEN_TOTAL", True, True, None, None),

        # --- Hepatitis B (infec_hepatitisb_nir.xlsx) ---
        ("HEPB_POP_U1", "Projected Population Under 1 (HepB file)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("HEPB_SCREEN_10_14", "Screened for Hepatitis B (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("HEPB_SCREEN_15_19", "Screened for Hepatitis B (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("HEPB_SCREEN_20_49", "Screened for Hepatitis B (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("HEPB_SCREEN_TOTAL", "Screened for Hepatitis B Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("HEPB_SCREEN_PCT", "Screened for Hepatitis B Percentage",
         "percentage", "quarterly", "percentage",
         100, "HEPB_POP_U1", True, False, None, None),
        ("HEPB_REACTIVE_10_14", "Reactive for Hepatitis B (10-14y)",
         "count", "quarterly", "count", 100, None, False, True, None, None),
        ("HEPB_REACTIVE_15_19", "Reactive for Hepatitis B (15-19y)",
         "count", "quarterly", "count", 100, None, False, True, None, None),
        ("HEPB_REACTIVE_20_49", "Reactive for Hepatitis B (20-49y)",
         "count", "quarterly", "count", 100, None, False, True, None, None),
        ("HEPB_REACTIVE_TOTAL", "Reactive for Hepatitis B Total",
         "count", "quarterly", "sum", 100, None, True, True, None, None),
        ("HEPB_REACTIVE_PCT", "Reactive for Hepatitis B Percentage (of screened)",
         "percentage", "quarterly", "percentage",
         100, "HEPB_SCREEN_TOTAL", True, True, None, None),

        # --- Syphilis (infec_syphilis_nir.xlsx) -- has extra Treated group ---
        ("SYPH_POP_U1", "Projected Population Under 1 (Syphilis file)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("SYPH_SCREEN_10_14", "Screened for Syphilis (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("SYPH_SCREEN_15_19", "Screened for Syphilis (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("SYPH_SCREEN_20_49", "Screened for Syphilis (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("SYPH_SCREEN_TOTAL", "Screened for Syphilis Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("SYPH_SCREEN_PCT", "Screened for Syphilis Percentage",
         "percentage", "quarterly", "percentage",
         100, "SYPH_POP_U1", True, False, None, None),
        ("SYPH_REACTIVE_10_14", "Reactive for Syphilis (10-14y)",
         "count", "quarterly", "count", 100, None, False, True, None, None),
        ("SYPH_REACTIVE_15_19", "Reactive for Syphilis (15-19y)",
         "count", "quarterly", "count", 100, None, False, True, None, None),
        ("SYPH_REACTIVE_20_49", "Reactive for Syphilis (20-49y)",
         "count", "quarterly", "count", 100, None, False, True, None, None),
        ("SYPH_REACTIVE_TOTAL", "Reactive for Syphilis Total",
         "count", "quarterly", "sum", 100, None, True, True, None, None),
        ("SYPH_REACTIVE_PCT", "Reactive for Syphilis Percentage (of screened)",
         "percentage", "quarterly", "percentage",
         100, "SYPH_SCREEN_TOTAL", True, True, None, None),
        ("SYPH_TREATED_10_14", "Treated for Syphilis, Reactive Women (10-14y)",
         "count", "quarterly", "count", 100, None, False, True, None, None),
        ("SYPH_TREATED_15_19", "Treated for Syphilis, Reactive Women (15-19y)",
         "count", "quarterly", "count", 100, None, False, True, None, None),
        ("SYPH_TREATED_20_49", "Treated for Syphilis, Reactive Women (20-49y)",
         "count", "quarterly", "count", 100, None, False, True, None, None),
        ("SYPH_TREATED_TOTAL", "Treated for Syphilis Total",
         "count", "quarterly", "sum", 100, None, True, True, None, None),
        ("SYPH_TREATED_PCT", "Treated for Syphilis Percentage (of reactive)",
         "percentage", "quarterly", "percentage",
         100, "SYPH_REACTIVE_TOTAL", True, True, None, None),
    ],

    # =================================================
    # WASH -- Water (envi_water_nir.xlsx)
    # Household-level basic safe water supply (BSWS Levels I/II/III) and
    # safely managed drinking water services (SMDWS). Municipality-level
    # (68 rows), quarterly only, no age/sex, no sensitive indicators.
    # Denominator for every percentage is Projected Number of Households.
    # =================================================
    "WASH": [
        ("WASH_WTR_PROJ_HH", "Projected Number of Households (Water file)",
         "count", "quarterly", "count", 100, None, False, False, None, None),

        # --- 1. With Basic Safe Water Supply (BSWS), by level ---
        ("WASH_WTR_BSWS_L1", "With BSWS Level I",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("WASH_WTR_BSWS_L1_PCT", "With BSWS Level I Percentage",
         "percentage", "quarterly", "percentage",
         100, "WASH_WTR_PROJ_HH", True, False, None, None),
        ("WASH_WTR_BSWS_L2", "With BSWS Level II",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("WASH_WTR_BSWS_L2_PCT", "With BSWS Level II Percentage",
         "percentage", "quarterly", "percentage",
         100, "WASH_WTR_PROJ_HH", True, False, None, None),
        ("WASH_WTR_BSWS_L3", "With BSWS Level III",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("WASH_WTR_BSWS_L3_PCT", "With BSWS Level III Percentage",
         "percentage", "quarterly", "percentage",
         100, "WASH_WTR_PROJ_HH", True, False, None, None),
        ("WASH_WTR_BSWS_TOTAL", "With BSWS Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("WASH_WTR_BSWS_TOTAL_PCT", "With BSWS Total Percentage",
         "percentage", "quarterly", "percentage",
         100, "WASH_WTR_PROJ_HH", True, False, None, None),

        # --- 2. Safely Managed Drinking Water Services ---
        ("WASH_WTR_SMDWS", "Safely Managed Drinking Water Services",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("WASH_WTR_SMDWS_PCT", "Safely Managed Drinking Water Services Percentage",
         "percentage", "quarterly", "percentage",
         100, "WASH_WTR_PROJ_HH", True, False, None, None),
    ],

    # =================================================
    # GERIATRIC -- Screening (ncd_geriatric_nir.xlsx, File 1)
    # Senior Citizen (60+) screening across 9 domains using the DOH
    # Geriatric Screening Tool, plus an "at least one positive" union count
    # and care-plan/referral follow-up. Province/HUC rollup (5 rows),
    # quarterly + annual, Male/Female split (no age brackets), no sensitive
    # indicators. Every domain percentage divides by GER_SCREENED_TOTAL;
    # care-plan percentage divides by GER_ATLEASTONE_TOTAL (only those with
    # a positive finding are eligible for a care plan).
    # =================================================
    "GERIATRIC": [
        ("GER_POP", "Projected Population of Senior Citizens (60+)",
         "count", "quarterly", "count", 100, None, False, False, None, None),

        # --- Screened using the Geriatric Screening Tool ---
        ("GER_SCREENED_MALE", "Screened with Geriatric Tool, Male",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_SCREENED_FEMALE", "Screened with Geriatric Tool, Female",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_SCREENED_TOTAL", "Screened with Geriatric Tool, Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("GER_SCREENED_PCT", "Screened with Geriatric Tool, Percentage",
         "percentage", "quarterly", "percentage",
         100, "GER_POP", True, False, None, None),

        # --- Domain 1: Memory ---
        ("GER_MEMORY_MALE", "Positive Memory Screening, Male",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_MEMORY_FEMALE", "Positive Memory Screening, Female",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_MEMORY_TOTAL", "Positive Memory Screening, Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("GER_MEMORY_PCT", "Positive Memory Screening, Percentage",
         "percentage", "quarterly", "percentage",
         100, "GER_SCREENED_TOTAL", True, False, None, None),

        # --- Domain 2: Depression ---
        ("GER_DEPRESSION_MALE", "Positive Depression Screening, Male",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_DEPRESSION_FEMALE", "Positive Depression Screening, Female",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_DEPRESSION_TOTAL", "Positive Depression Screening, Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("GER_DEPRESSION_PCT", "Positive Depression Screening, Percentage",
         "percentage", "quarterly", "percentage",
         100, "GER_SCREENED_TOTAL", True, False, None, None),

        # --- Domain 3: Polypharmacy ---
        ("GER_POLYPHARMACY_MALE", "Positive Polypharmacy Screening, Male",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_POLYPHARMACY_FEMALE", "Positive Polypharmacy Screening, Female",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_POLYPHARMACY_TOTAL", "Positive Polypharmacy Screening, Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("GER_POLYPHARMACY_PCT", "Positive Polypharmacy Screening, Percentage",
         "percentage", "quarterly", "percentage",
         100, "GER_SCREENED_TOTAL", True, False, None, None),

        # --- Domain 4: Urinary Incontinence ---
        ("GER_URININCONT_MALE", "Positive Urinary Incontinence Screening, Male",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_URININCONT_FEMALE", "Positive Urinary Incontinence Screening, Female",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_URININCONT_TOTAL", "Positive Urinary Incontinence Screening, Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("GER_URININCONT_PCT", "Positive Urinary Incontinence Screening, Percentage",
         "percentage", "quarterly", "percentage",
         100, "GER_SCREENED_TOTAL", True, False, None, None),

        # --- Domain 5: Functional Capacity ---
        ("GER_FUNCCAP_MALE", "Positive Functional Capacity Screening, Male",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_FUNCCAP_FEMALE", "Positive Functional Capacity Screening, Female",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_FUNCCAP_TOTAL", "Positive Functional Capacity Screening, Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("GER_FUNCCAP_PCT", "Positive Functional Capacity Screening, Percentage",
         "percentage", "quarterly", "percentage",
         100, "GER_SCREENED_TOTAL", True, False, None, None),

        # --- Domain 6: Malnutrition ---
        ("GER_MALNUTRITION_MALE", "Positive Malnutrition Screening, Male",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_MALNUTRITION_FEMALE", "Positive Malnutrition Screening, Female",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_MALNUTRITION_TOTAL", "Positive Malnutrition Screening, Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("GER_MALNUTRITION_PCT", "Positive Malnutrition Screening, Percentage",
         "percentage", "quarterly", "percentage",
         100, "GER_SCREENED_TOTAL", True, False, None, None),

        # --- Domain 7: Hearing ---
        ("GER_HEARING_MALE", "Positive Hearing Screening, Male",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_HEARING_FEMALE", "Positive Hearing Screening, Female",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_HEARING_TOTAL", "Positive Hearing Screening, Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("GER_HEARING_PCT", "Positive Hearing Screening, Percentage",
         "percentage", "quarterly", "percentage",
         100, "GER_SCREENED_TOTAL", True, False, None, None),

        # --- Domain 8: Vision ---
        ("GER_VISION_MALE", "Positive Vision Screening, Male",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_VISION_FEMALE", "Positive Vision Screening, Female",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_VISION_TOTAL", "Positive Vision Screening, Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("GER_VISION_PCT", "Positive Vision Screening, Percentage",
         "percentage", "quarterly", "percentage",
         100, "GER_SCREENED_TOTAL", True, False, None, None),

        # --- Domain 9: Fall Risk ---
        ("GER_FALLRISK_MALE", "Positive Fall Risk Screening, Male",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_FALLRISK_FEMALE", "Positive Fall Risk Screening, Female",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_FALLRISK_TOTAL", "Positive Fall Risk Screening, Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("GER_FALLRISK_PCT", "Positive Fall Risk Screening, Percentage",
         "percentage", "quarterly", "percentage",
         100, "GER_SCREENED_TOTAL", True, False, None, None),

        # --- With at least one positive screening (deduplicated union) ---
        ("GER_ATLEASTONE_MALE", "With At Least One Positive Screening, Male",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_ATLEASTONE_FEMALE", "With At Least One Positive Screening, Female",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_ATLEASTONE_TOTAL", "With At Least One Positive Screening, Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("GER_ATLEASTONE_PCT", "With At Least One Positive Screening, Percentage",
         "percentage", "quarterly", "percentage",
         100, "GER_SCREENED_TOTAL", True, False, None, None),

        # --- Provided with a care plan or referred ---
        ("GER_CAREPLAN_MALE", "Provided Care Plan or Referred, Male",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_CAREPLAN_FEMALE", "Provided Care Plan or Referred, Female",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("GER_CAREPLAN_TOTAL", "Provided Care Plan or Referred, Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("GER_CAREPLAN_PCT", "Provided Care Plan or Referred, Percentage",
         "percentage", "quarterly", "percentage",
         100, "GER_ATLEASTONE_TOTAL", True, False, None, None),
    ],

    # =================================================
    # MATERNAL CARE -- Prenatal (8 files, quarterly + annual)
    # No sensitive indicators. Files 2-7 divide by a "Projected Population
    # (Under 1)" column used as a live-cohort proxy for expected pregnancies
    # (per-file population column, matching the Immunization precedent).
    # Recompute rules (never trust the Excel value, see maternal_care_prenatal.md):
    #  - Anemia/GD "positive" percentages divide by the same-bracket SCREENED
    #    /TESTED count, not population (File 6's header mislabels this).
    #  - 8ANC "completed" percentages divide by the same-bracket TRACKED count;
    #    per-bracket tracked/completed are per-bracket sums, not group totals.
    # =================================================
    "MATERNAL_CARE": [
        # ---- File 2: Nutritional Status / BMI ----
        ("PRE_BMI_POP", "Prenatal BMI: Projected Population (Under 1) proxy",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_BMI_NORMAL_10_14", "Prenatal Normal BMI (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_BMI_NORMAL_15_19", "Prenatal Normal BMI (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_BMI_NORMAL_20_49", "Prenatal Normal BMI (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_BMI_NORMAL_TOTAL", "Prenatal Normal BMI Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_BMI_NORMAL_PCT", "Prenatal Normal BMI Percentage",
         "percentage", "quarterly", "percentage", 100, "PRE_BMI_POP", True, False, None, None),
        ("PRE_BMI_LOW_10_14", "Prenatal Low BMI (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_BMI_LOW_15_19", "Prenatal Low BMI (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_BMI_LOW_20_49", "Prenatal Low BMI (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_BMI_LOW_TOTAL", "Prenatal Low BMI Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_BMI_LOW_PCT", "Prenatal Low BMI Percentage",
         "percentage", "quarterly", "percentage", 100, "PRE_BMI_POP", True, False, None, None),
        ("PRE_BMI_HIGH_10_14", "Prenatal High BMI (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_BMI_HIGH_15_19", "Prenatal High BMI (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_BMI_HIGH_20_49", "Prenatal High BMI (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_BMI_HIGH_TOTAL", "Prenatal High BMI Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_BMI_HIGH_PCT", "Prenatal High BMI Percentage",
         "percentage", "quarterly", "percentage", 100, "PRE_BMI_POP", True, False, None, None),

        # ---- File 3: Td / Td2+ vaccination ----
        ("PRE_TD_POP", "Prenatal Td: Projected Population (Under 1) proxy",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_TD1_10_14", "Prenatal Td 1st Pregnancy (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_TD1_10_14_PCT", "Prenatal Td 1st Pregnancy Percentage (10-14y)",
         "percentage", "quarterly", "percentage", 100, "PRE_TD_POP", True, False, None, None),
        ("PRE_TD1_15_19", "Prenatal Td 1st Pregnancy (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_TD1_15_19_PCT", "Prenatal Td 1st Pregnancy Percentage (15-19y)",
         "percentage", "quarterly", "percentage", 100, "PRE_TD_POP", True, False, None, None),
        ("PRE_TD1_20_49", "Prenatal Td 1st Pregnancy (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_TD1_20_49_PCT", "Prenatal Td 1st Pregnancy Percentage (20-49y)",
         "percentage", "quarterly", "percentage", 100, "PRE_TD_POP", True, False, None, None),
        ("PRE_TD1_TOTAL", "Prenatal Td 1st Pregnancy Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_TD1_TOTAL_PCT", "Prenatal Td 1st Pregnancy Total Percentage",
         "percentage", "quarterly", "percentage", 100, "PRE_TD_POP", True, False, None, None),
        ("PRE_TD2PLUS_10_14", "Prenatal Td2+ (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_TD2PLUS_10_14_PCT", "Prenatal Td2+ Percentage (10-14y)",
         "percentage", "quarterly", "percentage", 100, "PRE_TD_POP", True, False, None, None),
        ("PRE_TD2PLUS_15_19", "Prenatal Td2+ (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_TD2PLUS_15_19_PCT", "Prenatal Td2+ Percentage (15-19y)",
         "percentage", "quarterly", "percentage", 100, "PRE_TD_POP", True, False, None, None),
        ("PRE_TD2PLUS_20_49", "Prenatal Td2+ (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_TD2PLUS_20_49_PCT", "Prenatal Td2+ Percentage (20-49y)",
         "percentage", "quarterly", "percentage", 100, "PRE_TD_POP", True, False, None, None),
        ("PRE_TD2PLUS_TOTAL", "Prenatal Td2+ Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_TD2PLUS_TOTAL_PCT", "Prenatal Td2+ Total Percentage",
         "percentage", "quarterly", "percentage", 100, "PRE_TD_POP", True, False, None, None),

        # ---- File 4: Micronutrient supplementation (IFA / MM / CC) ----
        ("PRE_SUPP_POP", "Prenatal Supplementation: Projected Population (Under 1) proxy",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_IFA_10_14", "Prenatal IFA (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_IFA_10_14_PCT", "Prenatal IFA Percentage (10-14y)",
         "percentage", "quarterly", "percentage", 100, "PRE_SUPP_POP", True, False, None, None),
        ("PRE_IFA_15_19", "Prenatal IFA (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_IFA_15_19_PCT", "Prenatal IFA Percentage (15-19y)",
         "percentage", "quarterly", "percentage", 100, "PRE_SUPP_POP", True, False, None, None),
        ("PRE_IFA_20_49", "Prenatal IFA (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_IFA_20_49_PCT", "Prenatal IFA Percentage (20-49y)",
         "percentage", "quarterly", "percentage", 100, "PRE_SUPP_POP", True, False, None, None),
        ("PRE_IFA_TOTAL", "Prenatal IFA Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_IFA_TOTAL_PCT", "Prenatal IFA Total Percentage",
         "percentage", "quarterly", "percentage", 100, "PRE_SUPP_POP", True, False, None, None),
        ("PRE_MM_10_14", "Prenatal Multiple Micronutrients (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_MM_10_14_PCT", "Prenatal Multiple Micronutrients Percentage (10-14y)",
         "percentage", "quarterly", "percentage", 100, "PRE_SUPP_POP", True, False, None, None),
        ("PRE_MM_15_19", "Prenatal Multiple Micronutrients (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_MM_15_19_PCT", "Prenatal Multiple Micronutrients Percentage (15-19y)",
         "percentage", "quarterly", "percentage", 100, "PRE_SUPP_POP", True, False, None, None),
        ("PRE_MM_20_49", "Prenatal Multiple Micronutrients (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_MM_20_49_PCT", "Prenatal Multiple Micronutrients Percentage (20-49y)",
         "percentage", "quarterly", "percentage", 100, "PRE_SUPP_POP", True, False, None, None),
        ("PRE_MM_TOTAL", "Prenatal Multiple Micronutrients Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_MM_TOTAL_PCT", "Prenatal Multiple Micronutrients Total Percentage",
         "percentage", "quarterly", "percentage", 100, "PRE_SUPP_POP", True, False, None, None),
        ("PRE_CC_10_14", "Prenatal Calcium Carbonate (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_CC_10_14_PCT", "Prenatal Calcium Carbonate Percentage (10-14y)",
         "percentage", "quarterly", "percentage", 100, "PRE_SUPP_POP", True, False, None, None),
        ("PRE_CC_15_19", "Prenatal Calcium Carbonate (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_CC_15_19_PCT", "Prenatal Calcium Carbonate Percentage (15-19y)",
         "percentage", "quarterly", "percentage", 100, "PRE_SUPP_POP", True, False, None, None),
        ("PRE_CC_20_49", "Prenatal Calcium Carbonate (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_CC_20_49_PCT", "Prenatal Calcium Carbonate Percentage (20-49y)",
         "percentage", "quarterly", "percentage", 100, "PRE_SUPP_POP", True, False, None, None),
        ("PRE_CC_TOTAL", "Prenatal Calcium Carbonate Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_CC_TOTAL_PCT", "Prenatal Calcium Carbonate Total Percentage",
         "percentage", "quarterly", "percentage", 100, "PRE_SUPP_POP", True, False, None, None),

        # ---- File 7: Deworming ----
        ("PRE_DEWORM_POP", "Prenatal Deworming: Projected Population (Under 1) proxy",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_DEWORM_10_14", "Prenatal Deworming (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_DEWORM_10_14_PCT", "Prenatal Deworming Percentage (10-14y)",
         "percentage", "quarterly", "percentage", 100, "PRE_DEWORM_POP", True, False, None, None),
        ("PRE_DEWORM_15_19", "Prenatal Deworming (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_DEWORM_15_19_PCT", "Prenatal Deworming Percentage (15-19y)",
         "percentage", "quarterly", "percentage", 100, "PRE_DEWORM_POP", True, False, None, None),
        ("PRE_DEWORM_20_49", "Prenatal Deworming (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_DEWORM_20_49_PCT", "Prenatal Deworming Percentage (20-49y)",
         "percentage", "quarterly", "percentage", 100, "PRE_DEWORM_POP", True, False, None, None),
        ("PRE_DEWORM_TOTAL", "Prenatal Deworming Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_DEWORM_TOTAL_PCT", "Prenatal Deworming Total Percentage",
         "percentage", "quarterly", "percentage", 100, "PRE_DEWORM_POP", True, False, None, None),

        # ---- File 5: Anemia screening (positive tier divides by TESTED) ----
        ("PRE_ANEMIA_POP", "Prenatal Anemia: Projected Population (Under 1) proxy",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_ANEMIA_TESTED_10_14", "Prenatal Anemia Tested (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_ANEMIA_TESTED_10_14_PCT", "Prenatal Anemia Tested Percentage (10-14y)",
         "percentage", "quarterly", "percentage", 100, "PRE_ANEMIA_POP", True, False, None, None),
        ("PRE_ANEMIA_TESTED_15_19", "Prenatal Anemia Tested (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_ANEMIA_TESTED_15_19_PCT", "Prenatal Anemia Tested Percentage (15-19y)",
         "percentage", "quarterly", "percentage", 100, "PRE_ANEMIA_POP", True, False, None, None),
        ("PRE_ANEMIA_TESTED_20_49", "Prenatal Anemia Tested (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_ANEMIA_TESTED_20_49_PCT", "Prenatal Anemia Tested Percentage (20-49y)",
         "percentage", "quarterly", "percentage", 100, "PRE_ANEMIA_POP", True, False, None, None),
        ("PRE_ANEMIA_TESTED_TOTAL", "Prenatal Anemia Tested Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_ANEMIA_TESTED_TOTAL_PCT", "Prenatal Anemia Tested Total Percentage",
         "percentage", "quarterly", "percentage", 100, "PRE_ANEMIA_POP", True, False, None, None),
        ("PRE_ANEMIA_POSITIVE_10_14", "Prenatal Anemia Diagnosed (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_ANEMIA_POSITIVE_10_14_PCT", "Prenatal Anemia Diagnosed Percentage of Tested (10-14y)",
         "percentage", "quarterly", "percentage", 100, "PRE_ANEMIA_TESTED_10_14", True, False, None, None),
        ("PRE_ANEMIA_POSITIVE_15_19", "Prenatal Anemia Diagnosed (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_ANEMIA_POSITIVE_15_19_PCT", "Prenatal Anemia Diagnosed Percentage of Tested (15-19y)",
         "percentage", "quarterly", "percentage", 100, "PRE_ANEMIA_TESTED_15_19", True, False, None, None),
        ("PRE_ANEMIA_POSITIVE_20_49", "Prenatal Anemia Diagnosed (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_ANEMIA_POSITIVE_20_49_PCT", "Prenatal Anemia Diagnosed Percentage of Tested (20-49y)",
         "percentage", "quarterly", "percentage", 100, "PRE_ANEMIA_TESTED_20_49", True, False, None, None),
        ("PRE_ANEMIA_POSITIVE_TOTAL", "Prenatal Anemia Diagnosed Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_ANEMIA_POSITIVE_TOTAL_PCT", "Prenatal Anemia Diagnosed Total Percentage of Tested",
         "percentage", "quarterly", "percentage", 100, "PRE_ANEMIA_TESTED_TOTAL", True, False, None, None),

        # ---- File 6: GD screening (positive tier divides by SCREENED, not pop) ----
        ("PRE_GD_POP", "Prenatal GD: Projected Population (Under 1) proxy",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_GD_SCREENED_10_14", "Prenatal GD Screened (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_GD_SCREENED_10_14_PCT", "Prenatal GD Screened Percentage (10-14y)",
         "percentage", "quarterly", "percentage", 100, "PRE_GD_POP", True, False, None, None),
        ("PRE_GD_SCREENED_15_19", "Prenatal GD Screened (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_GD_SCREENED_15_19_PCT", "Prenatal GD Screened Percentage (15-19y)",
         "percentage", "quarterly", "percentage", 100, "PRE_GD_POP", True, False, None, None),
        ("PRE_GD_SCREENED_20_49", "Prenatal GD Screened (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_GD_SCREENED_20_49_PCT", "Prenatal GD Screened Percentage (20-49y)",
         "percentage", "quarterly", "percentage", 100, "PRE_GD_POP", True, False, None, None),
        ("PRE_GD_SCREENED_TOTAL", "Prenatal GD Screened Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_GD_SCREENED_TOTAL_PCT", "Prenatal GD Screened Total Percentage",
         "percentage", "quarterly", "percentage", 100, "PRE_GD_POP", True, False, None, None),
        ("PRE_GD_POSITIVE_10_14", "Prenatal GD Positive (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_GD_POSITIVE_10_14_PCT", "Prenatal GD Positive Percentage of Screened (10-14y)",
         "percentage", "quarterly", "percentage", 100, "PRE_GD_SCREENED_10_14", True, False, None, None),
        ("PRE_GD_POSITIVE_15_19", "Prenatal GD Positive (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_GD_POSITIVE_15_19_PCT", "Prenatal GD Positive Percentage of Screened (15-19y)",
         "percentage", "quarterly", "percentage", 100, "PRE_GD_SCREENED_15_19", True, False, None, None),
        ("PRE_GD_POSITIVE_20_49", "Prenatal GD Positive (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_GD_POSITIVE_20_49_PCT", "Prenatal GD Positive Percentage of Screened (20-49y)",
         "percentage", "quarterly", "percentage", 100, "PRE_GD_SCREENED_20_49", True, False, None, None),
        ("PRE_GD_POSITIVE_TOTAL", "Prenatal GD Positive Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_GD_POSITIVE_TOTAL_PCT", "Prenatal GD Positive Total Percentage of Screened",
         "percentage", "quarterly", "percentage", 100, "PRE_GD_SCREENED_TOTAL", True, False, None, None),

        # ---- File 1: 8ANC completion (municipality; chained TRACKED denominator) ----
        ("PRE_8ANC_RESIDENT_10_14", "8ANC Delivered & Tracked Resident (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_8ANC_RESIDENT_15_19", "8ANC Delivered & Tracked Resident (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_8ANC_RESIDENT_20_49", "8ANC Delivered & Tracked Resident (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_8ANC_RESIDENT_TOTAL", "8ANC Delivered & Tracked Resident Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_8ANC_TRANSIN_10_14", "8ANC Trans-in (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_8ANC_TRANSIN_15_19", "8ANC Trans-in (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_8ANC_TRANSIN_20_49", "8ANC Trans-in (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_8ANC_TRANSIN_TOTAL", "8ANC Trans-in Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_8ANC_TRANSOUT_10_14", "8ANC Trans-out before completion (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_8ANC_TRANSOUT_15_19", "8ANC Trans-out before completion (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_8ANC_TRANSOUT_20_49", "8ANC Trans-out before completion (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_8ANC_TRANSOUT_TOTAL", "8ANC Trans-out Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_8ANC_TRACKED_10_14", "8ANC Total Tracked (10-14y)",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_8ANC_TRACKED_15_19", "8ANC Total Tracked (15-19y)",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_8ANC_TRACKED_20_49", "8ANC Total Tracked (20-49y)",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_8ANC_TRACKED_TOTAL", "8ANC Total Tracked, Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_8ANC_ONSCHED_10_14", "8ANC Given ANC on Schedule Resident (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_8ANC_ONSCHED_15_19", "8ANC Given ANC on Schedule Resident (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_8ANC_ONSCHED_20_49", "8ANC Given ANC on Schedule Resident (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_8ANC_ONSCHED_TOTAL", "8ANC Given ANC on Schedule Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_8ANC_TRANSIN_DONE_10_14", "8ANC Completed Trans-in (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_8ANC_TRANSIN_DONE_15_19", "8ANC Completed Trans-in (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_8ANC_TRANSIN_DONE_20_49", "8ANC Completed Trans-in (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_8ANC_TRANSIN_DONE_TOTAL", "8ANC Completed Trans-in Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_8ANC_COMPLETED_10_14", "8ANC Completed >=8 Visits (10-14y)",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_8ANC_COMPLETED_10_14_PCT", "8ANC Completion Rate (10-14y)",
         "percentage", "quarterly", "percentage", 100, "PRE_8ANC_TRACKED_10_14", True, False, None, None),
        ("PRE_8ANC_COMPLETED_15_19", "8ANC Completed >=8 Visits (15-19y)",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_8ANC_COMPLETED_15_19_PCT", "8ANC Completion Rate (15-19y)",
         "percentage", "quarterly", "percentage", 100, "PRE_8ANC_TRACKED_15_19", True, False, None, None),
        ("PRE_8ANC_COMPLETED_20_49", "8ANC Completed >=8 Visits (20-49y)",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_8ANC_COMPLETED_20_49_PCT", "8ANC Completion Rate (20-49y)",
         "percentage", "quarterly", "percentage", 100, "PRE_8ANC_TRACKED_20_49", True, False, None, None),
        ("PRE_8ANC_COMPLETED_TOTAL", "8ANC Completed >=8 Visits Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_8ANC_COMPLETED_TOTAL_PCT", "8ANC Completion Rate Total",
         "percentage", "quarterly", "percentage", 100, "PRE_8ANC_TRACKED_TOTAL", True, False, None, None),

        # ---- File 8a: BP measured during ANC visits (municipality; chained) ----
        ("PRE_BP_ANCVISIT_10_14", "Prenatal ANC Visits (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_BP_ANCVISIT_15_19", "Prenatal ANC Visits (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_BP_ANCVISIT_20_49", "Prenatal ANC Visits (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_BP_ANCVISIT_TOTAL", "Prenatal ANC Visits Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_BP_MEASURED_10_14", "Prenatal BP Measured (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_BP_MEASURED_10_14_PCT", "Prenatal BP Measured Percentage (10-14y)",
         "percentage", "quarterly", "percentage", 100, "PRE_BP_ANCVISIT_10_14", True, False, None, None),
        ("PRE_BP_MEASURED_15_19", "Prenatal BP Measured (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_BP_MEASURED_15_19_PCT", "Prenatal BP Measured Percentage (15-19y)",
         "percentage", "quarterly", "percentage", 100, "PRE_BP_ANCVISIT_15_19", True, False, None, None),
        ("PRE_BP_MEASURED_20_49", "Prenatal BP Measured (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_BP_MEASURED_20_49_PCT", "Prenatal BP Measured Percentage (20-49y)",
         "percentage", "quarterly", "percentage", 100, "PRE_BP_ANCVISIT_20_49", True, False, None, None),
        ("PRE_BP_MEASURED_TOTAL", "Prenatal BP Measured Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_BP_MEASURED_TOTAL_PCT", "Prenatal BP Measured Total Percentage",
         "percentage", "quarterly", "percentage", 100, "PRE_BP_ANCVISIT_TOTAL", True, False, None, None),

        # ---- File 8b: High BP identified & referred (municipality; chained) ----
        ("PRE_HPN_IDENTIFIED_10_14", "Prenatal High BP Identified (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_HPN_IDENTIFIED_15_19", "Prenatal High BP Identified (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_HPN_IDENTIFIED_20_49", "Prenatal High BP Identified (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_HPN_IDENTIFIED_TOTAL", "Prenatal High BP Identified Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_HPN_REFERRED_10_14", "Prenatal High BP Referred (10-14y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_HPN_REFERRED_10_14_PCT", "Prenatal High BP Referred Percentage (10-14y)",
         "percentage", "quarterly", "percentage", 100, "PRE_HPN_IDENTIFIED_10_14", True, False, None, None),
        ("PRE_HPN_REFERRED_15_19", "Prenatal High BP Referred (15-19y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_HPN_REFERRED_15_19_PCT", "Prenatal High BP Referred Percentage (15-19y)",
         "percentage", "quarterly", "percentage", 100, "PRE_HPN_IDENTIFIED_15_19", True, False, None, None),
        ("PRE_HPN_REFERRED_20_49", "Prenatal High BP Referred (20-49y)",
         "count", "quarterly", "count", 100, None, False, False, None, None),
        ("PRE_HPN_REFERRED_20_49_PCT", "Prenatal High BP Referred Percentage (20-49y)",
         "percentage", "quarterly", "percentage", 100, "PRE_HPN_IDENTIFIED_20_49", True, False, None, None),
        ("PRE_HPN_REFERRED_TOTAL", "Prenatal High BP Referred Total",
         "count", "quarterly", "sum", 100, None, True, False, None, None),
        ("PRE_HPN_REFERRED_TOTAL_PCT", "Prenatal High BP Referred Total Percentage",
         "percentage", "quarterly", "percentage", 100, "PRE_HPN_IDENTIFIED_TOTAL", True, False, None, None),
    ],
}

# =====================================================
# SEED FUNCTION
# =====================================================

def seed_indicators():
    conn = psycopg2.connect(**get_db_config())
    cur = conn.cursor()

    total_inserted = 0
    total_skipped = 0

    for program_code, indicators in INDICATORS.items():

        # Get program id
        cur.execute(
            "SELECT id FROM programs WHERE code = %s",
            (program_code,)
        )
        result = cur.fetchone()
        if not result:
            print(f"WARNING: Program '{program_code}' not found. Skipping.")
            continue
        program_id = result[0]

        for ind in indicators:
            (code, name, unit, frequency_type, formula_type,
             rate_multiplier, denominator_source, is_computed,
             is_sensitive, target_value, target_year) = ind

            # Check if already exists
            cur.execute(
                "SELECT id FROM indicators WHERE code = %s",
                (code,)
            )
            if cur.fetchone():
                print(f"  SKIP (exists): {code}")
                total_skipped += 1
                continue

            # Insert
            cur.execute("""
                INSERT INTO indicators (
                    program_id, code, name, unit, frequency_type,
                    formula_type, rate_multiplier, denominator_source,
                    is_computed, is_sensitive, target_value, target_year,
                    year_introduced
                ) VALUES (
                    %s, %s, %s, %s, %s,
                    %s, %s, %s,
                    %s, %s, %s, %s,
                    2026
                )
            """, (
                program_id, code, name, unit, frequency_type,
                formula_type, rate_multiplier, denominator_source,
                is_computed, is_sensitive, target_value, target_year
            ))
            print(f"  INSERTED: {code}")
            total_inserted += 1

    conn.commit()
    cur.close()
    conn.close()

    print(f"\nDone. Inserted: {total_inserted} | Skipped: {total_skipped}")


if __name__ == "__main__":
    seed_indicators()