# seed_indicators.py
# Auto-generates and inserts all FHSIS indicators into the database
# Run this script once to populate the indicators table
# Safe to run multiple times -- skips existing indicators

import os

import psycopg2

# =====================================================
# DATABASE CONNECTION
# Reads from environment (mirrors app/core/db.py) so the same script runs on
# the host and inside the Docker container (where DB_HOST=db).
# =====================================================
DB_CONFIG = {
    "host": os.getenv("DB_HOST", "localhost"),
    "port": int(os.getenv("DB_PORT", "5432")),
    "database": os.getenv("DB_NAME", "doh_nir_dashboard"),
    "user": os.getenv("DB_USER", "doh_admin"),
    "password": os.getenv("DB_PASSWORD", "doh_password_2026"),
}

# =====================================================
# INDICATOR DEFINITIONS
# Format per indicator:
# (code, name, unit, frequency_type, formula_type,
#  rate_multiplier, denominator_source, is_computed,
#  is_sensitive, target_value, target_year)
# =====================================================

INDICATORS = {

    # =================================================
    # CHILD CARE -- IMMUNIZATION
    # =================================================
    "CHILD_CARE": [

        # --- File 1: CPAB, BCG, HepaB ---
        # Population
        ("IMMUN_POP_0_11M", "Projected Population 0-11 Months",
         "count", "monthly", "count",
         100, None, False, False, None, None),

        # CPAB
        ("CPAB_MALE", "CPAB Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("CPAB_FEMALE", "CPAB Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("CPAB_TOTAL", "CPAB Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("CPAB_PCT", "CPAB Percentage",
         "percentage", "monthly", "percentage",
         100, "IMMUN_POP_0_11M", True, False, 0.95, 2026),

        # BCG within 24h
        ("BCG_24H_MALE", "BCG Within 24h Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("BCG_24H_FEMALE", "BCG Within 24h Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("BCG_24H_TOTAL", "BCG Within 24h Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("BCG_24H_PCT", "BCG Within 24h Percentage",
         "percentage", "monthly", "percentage",
         100, "IMMUN_POP_0_11M", True, False, None, None),

        # BCG >24h to 11m29d
        ("BCG_GT24H_MALE", "BCG >24h to 11m29d Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("BCG_GT24H_FEMALE", "BCG >24h to 11m29d Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("BCG_GT24H_TOTAL", "BCG >24h to 11m29d Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("BCG_GT24H_PCT", "BCG >24h to 11m29d Percentage",
         "percentage", "monthly", "percentage",
         100, "IMMUN_POP_0_11M", True, False, None, None),

        # HepaB within 24h
        ("HEPAB_24H_MALE", "HepaB Within 24h Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("HEPAB_24H_FEMALE", "HepaB Within 24h Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("HEPAB_24H_TOTAL", "HepaB Within 24h Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("HEPAB_24H_PCT", "HepaB Within 24h Percentage",
         "percentage", "monthly", "percentage",
         100, "IMMUN_POP_0_11M", True, False, None, None),

        # HepaB >24h to 14 days
        ("HEPAB_GT24H_MALE", "HepaB >24h to 14 Days Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("HEPAB_GT24H_FEMALE", "HepaB >24h to 14 Days Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("HEPAB_GT24H_TOTAL", "HepaB >24h to 14 Days Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("HEPAB_GT24H_PCT", "HepaB >24h to 14 Days Percentage",
         "percentage", "monthly", "percentage",
         100, "IMMUN_POP_0_11M", True, False, None, None),

        # --- File 4: DPT-HiB-HepB doses 1,2,3 ---
        # Current year population
        ("DPT_POP_2026", "DPT Projected Population 2026 (0-11 Months)",
         "count", "monthly", "count",
         100, None, False, False, None, None),

        # DPT dose 1 current year
        ("DPT1_MALE", "DPT-HiB-HepB Dose 1 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("DPT1_FEMALE", "DPT-HiB-HepB Dose 1 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("DPT1_TOTAL", "DPT-HiB-HepB Dose 1 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("DPT1_PCT", "DPT-HiB-HepB Dose 1 Percentage",
         "percentage", "monthly", "percentage",
         100, "DPT_POP_2026", True, False, None, None),

        # DPT dose 2 current year
        ("DPT2_MALE", "DPT-HiB-HepB Dose 2 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("DPT2_FEMALE", "DPT-HiB-HepB Dose 2 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("DPT2_TOTAL", "DPT-HiB-HepB Dose 2 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("DPT2_PCT", "DPT-HiB-HepB Dose 2 Percentage",
         "percentage", "monthly", "percentage",
         100, "DPT_POP_2026", True, False, None, None),

        # DPT dose 3 current year
        ("DPT3_MALE", "DPT-HiB-HepB Dose 3 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("DPT3_FEMALE", "DPT-HiB-HepB Dose 3 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("DPT3_TOTAL", "DPT-HiB-HepB Dose 3 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("DPT3_PCT", "DPT-HiB-HepB Dose 3 Percentage",
         "percentage", "monthly", "percentage",
         100, "DPT_POP_2026", True, False, None, None),

        # --- File 5: OPV doses 1,2,3 ---
        ("OPV_POP_2026", "OPV Projected Population 2026 (0-11 Months)",
         "count", "monthly", "count",
         100, None, False, False, None, None),

        ("OPV1_MALE", "OPV Dose 1 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("OPV1_FEMALE", "OPV Dose 1 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("OPV1_TOTAL", "OPV Dose 1 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("OPV1_PCT", "OPV Dose 1 Percentage",
         "percentage", "monthly", "percentage",
         100, "OPV_POP_2026", True, False, None, None),

        ("OPV2_MALE", "OPV Dose 2 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("OPV2_FEMALE", "OPV Dose 2 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("OPV2_TOTAL", "OPV Dose 2 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("OPV2_PCT", "OPV Dose 2 Percentage",
         "percentage", "monthly", "percentage",
         100, "OPV_POP_2026", True, False, None, None),

        ("OPV3_MALE", "OPV Dose 3 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("OPV3_FEMALE", "OPV Dose 3 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("OPV3_TOTAL", "OPV Dose 3 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("OPV3_PCT", "OPV Dose 3 Percentage",
         "percentage", "monthly", "percentage",
         100, "OPV_POP_2026", True, False, None, None),

        # --- File 6: IPV doses 1,2 ---
        ("IPV_POP_2026", "IPV Projected Population 2026 (0-11 Months)",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("IPV1_MALE", "IPV Dose 1 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("IPV1_FEMALE", "IPV Dose 1 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("IPV1_TOTAL", "IPV Dose 1 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("IPV1_PCT", "IPV Dose 1 Percentage",
         "percentage", "monthly", "percentage",
         100, "IPV_POP_2026", True, False, None, None),
        ("IPV2_MALE", "IPV Dose 2 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("IPV2_FEMALE", "IPV Dose 2 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("IPV2_TOTAL", "IPV Dose 2 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("IPV2_PCT", "IPV Dose 2 Percentage",
         "percentage", "monthly", "percentage",
         100, "IPV_POP_2026", True, False, None, None),

        # --- File 7: PCV doses 1,2,3 ---
        ("PCV_POP_2026", "PCV Projected Population 2026 (0-11 Months)",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("PCV1_MALE", "PCV Dose 1 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("PCV1_FEMALE", "PCV Dose 1 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("PCV1_TOTAL", "PCV Dose 1 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("PCV1_PCT", "PCV Dose 1 Percentage",
         "percentage", "monthly", "percentage",
         100, "PCV_POP_2026", True, False, None, None),
        ("PCV2_MALE", "PCV Dose 2 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("PCV2_FEMALE", "PCV Dose 2 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("PCV2_TOTAL", "PCV Dose 2 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("PCV2_PCT", "PCV Dose 2 Percentage",
         "percentage", "monthly", "percentage",
         100, "PCV_POP_2026", True, False, None, None),
        ("PCV3_MALE", "PCV Dose 3 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("PCV3_FEMALE", "PCV Dose 3 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("PCV3_TOTAL", "PCV Dose 3 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("PCV3_PCT", "PCV Dose 3 Percentage",
         "percentage", "monthly", "percentage",
         100, "PCV_POP_2026", True, False, None, None),

        # --- File 8: MMR 1/2 (FIC/CIC shared below) ---
        ("MMR_POP_2026", "MMR Projected Population 2026 (0-11 Months)",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("MMR1_MALE", "MMR Dose 1 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("MMR1_FEMALE", "MMR Dose 1 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("MMR1_TOTAL", "MMR Dose 1 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("MMR1_PCT", "MMR Dose 1 Percentage",
         "percentage", "monthly", "percentage",
         100, "MMR_POP_2026", True, False, None, None),
        ("MMR1_PREV_MALE", "MMR Dose 1 Male (Previous Year Cohort)",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("MMR1_PREV_FEMALE", "MMR Dose 1 Female (Previous Year Cohort)",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("MMR1_PREV_TOTAL", "MMR Dose 1 Total (Previous Year Cohort)",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("MMR1_PREV_PCT", "MMR Dose 1 Percentage (Previous Year Cohort)",
         "percentage", "monthly", "percentage",
         100, "IMMUN_POP_0_11M_PREV", True, False, None, None),
        ("MMR2_MALE", "MMR Dose 2 Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("MMR2_FEMALE", "MMR Dose 2 Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("MMR2_TOTAL", "MMR Dose 2 Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("MMR2_PCT", "MMR Dose 2 Percentage",
         "percentage", "monthly", "percentage",
         100, "IMMUN_POP_0_11M_PREV", True, False, None, None),

        # --- Management of the Sick: Vitamin A ---
        ("SICK_VITA_SEEN_611_MALE", "Sick Seen 6-11m Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("SICK_VITA_SEEN_611_FEMALE", "Sick Seen 6-11m Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("SICK_VITA_SEEN_611_TOTAL", "Sick Seen 6-11m Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("SICK_VITA_GIVEN_611_MALE", "Sick 6-11m Given Vitamin A Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("SICK_VITA_GIVEN_611_FEMALE", "Sick 6-11m Given Vitamin A Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("SICK_VITA_GIVEN_611_TOTAL", "Sick 6-11m Given Vitamin A Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("SICK_VITA_GIVEN_611_PCT", "Sick 6-11m Given Vitamin A Percentage",
         "percentage", "quarterly", "percentage",
         100, "SICK_VITA_SEEN_611_TOTAL", True, False, None, None),
        ("SICK_VITA_SEEN_1259_MALE", "Sick Seen 12-59m Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("SICK_VITA_SEEN_1259_FEMALE", "Sick Seen 12-59m Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("SICK_VITA_SEEN_1259_TOTAL", "Sick Seen 12-59m Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("SICK_VITA_GIVEN_1259_MALE", "Sick 12-59m Given Vitamin A Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("SICK_VITA_GIVEN_1259_FEMALE", "Sick 12-59m Given Vitamin A Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("SICK_VITA_GIVEN_1259_TOTAL", "Sick 12-59m Given Vitamin A Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("SICK_VITA_GIVEN_1259_PCT", "Sick 12-59m Given Vitamin A Percentage",
         "percentage", "quarterly", "percentage",
         100, "SICK_VITA_SEEN_1259_TOTAL", True, False, None, None),

        # --- Management of the Sick: Diarrhea & Pneumonia ---
        ("DIAR_SEEN_MALE", "Diarrhea Cases Seen Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("DIAR_SEEN_FEMALE", "Diarrhea Cases Seen Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("DIAR_SEEN_TOTAL", "Diarrhea Cases Seen Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("DIAR_ORS_MALE", "Diarrhea Given ORS Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("DIAR_ORS_FEMALE", "Diarrhea Given ORS Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("DIAR_ORS_TOTAL", "Diarrhea Given ORS Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("DIAR_ORS_PCT", "Diarrhea Given ORS Percentage",
         "percentage", "quarterly", "percentage",
         100, "DIAR_SEEN_TOTAL", True, False, None, None),
        ("DIAR_ORSZ_MALE", "Diarrhea Given ORS+Zinc Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("DIAR_ORSZ_FEMALE", "Diarrhea Given ORS+Zinc Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("DIAR_ORSZ_TOTAL", "Diarrhea Given ORS+Zinc Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("DIAR_ORSZ_PCT", "Diarrhea Given ORS+Zinc Percentage",
         "percentage", "quarterly", "percentage",
         100, "DIAR_SEEN_TOTAL", True, False, None, None),
        ("DIAR_COMBINED_TOTAL", "Diarrhea Combined Treatment Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("DIAR_COMBINED_PCT", "Diarrhea Combined Treatment Percentage",
         "percentage", "quarterly", "percentage",
         100, "DIAR_SEEN_TOTAL", True, False, None, None),
        ("PNEU_SEEN_MALE", "Pneumonia Cases Seen Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("PNEU_SEEN_FEMALE", "Pneumonia Cases Seen Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("PNEU_SEEN_TOTAL", "Pneumonia Cases Seen Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("PNEU_ABX_MALE", "Pneumonia Given Antibiotic Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("PNEU_ABX_FEMALE", "Pneumonia Given Antibiotic Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("PNEU_ABX_TOTAL", "Pneumonia Given Antibiotic Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("PNEU_ABX_PCT", "Pneumonia Given Antibiotic Percentage",
         "percentage", "quarterly", "percentage",
         100, "PNEU_SEEN_TOTAL", True, False, None, None),

        # --- Nutrition: File 1 Breastfeeding and LBW ---
        ("NUT_BF_LIVE_BIRTHS", "Live Births",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_BF_1H_MALE", "Breastfeeding Within 1 Hour Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_BF_1H_FEMALE", "Breastfeeding Within 1 Hour Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_BF_1H_TOTAL", "Breastfeeding Within 1 Hour Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("NUT_BF_1H_PCT", "Breastfeeding Within 1 Hour Percentage",
         "percentage", "quarterly", "percentage",
         100, "NUT_BF_LIVE_BIRTHS", True, False, None, None),
        ("NUT_LBW_COUNT", "Low Birth Weight Count",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_LBW_IRON_MALE", "LBW Given Iron Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_LBW_IRON_FEMALE", "LBW Given Iron Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_LBW_IRON_TOTAL", "LBW Given Iron Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("NUT_LBW_IRON_PCT", "LBW Given Iron Percentage",
         "percentage", "quarterly", "percentage",
         100, "NUT_LBW_COUNT", True, False, None, None),

        # --- Nutrition: Files 2-3 Vitamin A ---
        ("NUT_VITA_POP_611", "Projected Population 6-11 Months (Vitamin A)",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_VITA_611_MALE", "Vitamin A 6-11m Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_VITA_611_FEMALE", "Vitamin A 6-11m Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_VITA_611_TOTAL", "Vitamin A 6-11m Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("NUT_VITA_611_PCT", "Vitamin A 6-11m Percentage",
         "percentage", "quarterly", "percentage",
         100, "NUT_VITA_POP_611", True, False, None, None),
        ("NUT_VITA_POP_1259", "Projected Population 12-59 Months (Vitamin A)",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_VITA_1259_MALE", "Vitamin A 12-59m Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_VITA_1259_FEMALE", "Vitamin A 12-59m Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_VITA_1259_TOTAL", "Vitamin A 12-59m Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("NUT_VITA_1259_PCT", "Vitamin A 12-59m Percentage",
         "percentage", "quarterly", "percentage",
         100, "NUT_VITA_POP_1259", True, False, None, None),

        # --- Nutrition: File 4 MNP ---
        ("NUT_MNP_POP_611", "Projected Population 6-11 Months (MNP)",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_MNP_611_MALE", "MNP 6-11m Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_MNP_611_FEMALE", "MNP 6-11m Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_MNP_611_TOTAL", "MNP 6-11m Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("NUT_MNP_611_PCT", "MNP 6-11m Percentage",
         "percentage", "quarterly", "percentage",
         100, "NUT_MNP_POP_611", True, False, None, None),
        ("NUT_MNP_POP_1223", "Projected Population 12-23 Months (MNP)",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_MNP_1223_MALE", "MNP 12-23m Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_MNP_1223_FEMALE", "MNP 12-23m Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_MNP_1223_TOTAL", "MNP 12-23m Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("NUT_MNP_1223_PCT", "MNP 12-23m Percentage",
         "percentage", "quarterly", "percentage",
         100, "NUT_MNP_POP_1223", True, False, None, None),

        # --- Nutrition: File 5 LNS-SQ ---
        ("NUT_LNS_POP_611", "Projected Population 6-11 Months (LNS-SQ)",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_LNS_611_MALE", "LNS-SQ 6-11m Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_LNS_611_FEMALE", "LNS-SQ 6-11m Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_LNS_611_TOTAL", "LNS-SQ 6-11m Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("NUT_LNS_611_PCT", "LNS-SQ 6-11m Percentage",
         "percentage", "quarterly", "percentage",
         100, "NUT_LNS_POP_611", True, False, None, None),
        ("NUT_LNS_POP_1223", "Projected Population 12-23 Months (LNS-SQ)",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_LNS_1223_MALE", "LNS-SQ 12-23m Male",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_LNS_1223_FEMALE", "LNS-SQ 12-23m Female",
         "count", "quarterly", "count",
         100, None, False, False, None, None),
        ("NUT_LNS_1223_TOTAL", "LNS-SQ 12-23m Total",
         "count", "quarterly", "sum",
         100, None, True, False, None, None),
        ("NUT_LNS_1223_PCT", "LNS-SQ 12-23m Percentage",
         "percentage", "quarterly", "percentage",
         100, "NUT_LNS_POP_1223", True, False, None, None),

        # --- Nutrition: File 6 MAM & SAM (Annual) ---
        ("NUT_MAM_SEEN_MALE", "MAM Children Seen Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_SEEN_FEMALE", "MAM Children Seen Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_SEEN_TOTAL", "MAM Children Seen Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_MAM_ID_MALE", "MAM Identified Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_ID_FEMALE", "MAM Identified Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_ID_TOTAL", "MAM Identified Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_MAM_ID_PCT", "MAM Identified Percentage",
         "percentage", "annual", "percentage", 100, "NUT_MAM_SEEN_TOTAL", True, False, None, None),
        ("NUT_MAM_SFP_MALE", "MAM Enrolled SFP Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_SFP_FEMALE", "MAM Enrolled SFP Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_SFP_TOTAL", "MAM Enrolled SFP Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_MAM_SFP_PCT", "MAM Enrolled SFP Percentage",
         "percentage", "annual", "percentage", 100, "NUT_MAM_SEEN_TOTAL", True, False, None, None),
        ("NUT_MAM_CURED_MALE", "MAM Cured SFP Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_CURED_FEMALE", "MAM Cured SFP Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_CURED_TOTAL", "MAM Cured SFP Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_MAM_CURED_PCT", "MAM Cured SFP Percentage",
         "percentage", "annual", "percentage", 100, "NUT_MAM_SEEN_TOTAL", True, False, None, None),
        ("NUT_MAM_NONCURED_MALE", "MAM Non-cured SFP Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_NONCURED_FEMALE", "MAM Non-cured SFP Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_NONCURED_TOTAL", "MAM Non-cured SFP Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_MAM_NONCURED_PCT", "MAM Non-cured SFP Percentage",
         "percentage", "annual", "percentage", 100, "NUT_MAM_SEEN_TOTAL", True, False, None, None),
        ("NUT_MAM_DEFAULT_MALE", "MAM Defaulted SFP Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_DEFAULT_FEMALE", "MAM Defaulted SFP Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_DEFAULT_TOTAL", "MAM Defaulted SFP Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_MAM_DEFAULT_PCT", "MAM Defaulted SFP Percentage",
         "percentage", "annual", "percentage", 100, "NUT_MAM_SEEN_TOTAL", True, False, None, None),
        ("NUT_MAM_DIED_MALE", "MAM Died SFP Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_DIED_FEMALE", "MAM Died SFP Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_MAM_DIED_TOTAL", "MAM Died SFP Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_MAM_DIED_PCT", "MAM Died SFP Percentage",
         "percentage", "annual", "percentage", 100, "NUT_MAM_SEEN_TOTAL", True, False, None, None),
        ("NUT_SAM_SEEN_MALE", "SAM Children Seen Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_SEEN_FEMALE", "SAM Children Seen Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_SEEN_TOTAL", "SAM Children Seen Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_SAM_ID_MALE", "SAM Identified Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_ID_FEMALE", "SAM Identified Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_ID_TOTAL", "SAM Identified Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_SAM_ID_PCT", "SAM Identified Percentage",
         "percentage", "annual", "percentage", 100, "NUT_SAM_SEEN_TOTAL", True, False, None, None),
        ("NUT_SAM_OTC_MALE", "SAM Admitted OTC Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_OTC_FEMALE", "SAM Admitted OTC Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_OTC_TOTAL", "SAM Admitted OTC Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_SAM_OTC_PCT", "SAM Admitted OTC Percentage",
         "percentage", "annual", "percentage", 100, "NUT_SAM_SEEN_TOTAL", True, False, None, None),
        ("NUT_SAM_CURED_MALE", "SAM Cured OTC Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_CURED_FEMALE", "SAM Cured OTC Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_CURED_TOTAL", "SAM Cured OTC Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_SAM_CURED_PCT", "SAM Cured OTC Percentage",
         "percentage", "annual", "percentage", 100, "NUT_SAM_SEEN_TOTAL", True, False, None, None),
        ("NUT_SAM_NONCURED_MALE", "SAM Non-cured OTC Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_NONCURED_FEMALE", "SAM Non-cured OTC Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_NONCURED_TOTAL", "SAM Non-cured OTC Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_SAM_NONCURED_PCT", "SAM Non-cured OTC Percentage",
         "percentage", "annual", "percentage", 100, "NUT_SAM_SEEN_TOTAL", True, False, None, None),
        ("NUT_SAM_DEFAULT_MALE", "SAM Defaulted OTC Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_DEFAULT_FEMALE", "SAM Defaulted OTC Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_DEFAULT_TOTAL", "SAM Defaulted OTC Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_SAM_DEFAULT_PCT", "SAM Defaulted OTC Percentage",
         "percentage", "annual", "percentage", 100, "NUT_SAM_SEEN_TOTAL", True, False, None, None),
        ("NUT_SAM_DIED_MALE", "SAM Died OTC Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_DIED_FEMALE", "SAM Died OTC Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("NUT_SAM_DIED_TOTAL", "SAM Died OTC Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("NUT_SAM_DIED_PCT", "SAM Died OTC Percentage",
         "percentage", "annual", "percentage", 100, "NUT_SAM_SEEN_TOTAL", True, False, None, None),

        # FIC and CIC
        ("FIC_MALE", "Fully Immunized Child Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("FIC_FEMALE", "Fully Immunized Child Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("FIC_TOTAL", "Fully Immunized Child Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("FIC_PCT", "Fully Immunized Child Percentage",
         "percentage", "monthly", "percentage",
         100, "IMMUN_POP_0_11M_PREV", True, False, 0.95, 2026),

        ("CIC_MALE", "Completely Immunized Child Male",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("CIC_FEMALE", "Completely Immunized Child Female",
         "count", "monthly", "count",
         100, None, False, False, None, None),
        ("CIC_TOTAL", "Completely Immunized Child Total",
         "count", "monthly", "sum",
         100, None, True, False, None, None),
        ("CIC_PCT", "Completely Immunized Child Percentage",
         "percentage", "monthly", "percentage",
         100, "PREV_POP_MINUS_FIC", True, False, 0.95, 2026),

        ("PREV_POP_MINUS_FIC",
         "Previous Year Population Minus FIC (CIC Denominator)",
         "count", "monthly", "count",
         100, None, True, False, None, None),

        # Previous year population (for MMR2, FIC, CIC)
        ("IMMUN_POP_0_11M_PREV",
         "Projected Population 0-11 Months Previous Year",
         "count", "monthly", "count",
         100, None, False, False, None, None),

        # =================================================
        # CHILD CARE -- SBI (School-Based Immunization), annual
        # Denominator = enrolled learners (a column in the file, from DepEd),
        # not the health population table.
        # =================================================

        # --- File 9: G1 & G7 given Td vaccine ---
        ("SBI_TD_G1_ENROLLED", "Td: Grade 1 Enrolled Learners",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_TD_G1_MALE", "Td: Grade 1 Given Td Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_TD_G1_FEMALE", "Td: Grade 1 Given Td Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_TD_G1_TOTAL", "Td: Grade 1 Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("SBI_TD_G1_PCT", "Td: Grade 1 Percentage",
         "percentage", "annual", "percentage",
         100, "SBI_TD_G1_ENROLLED", True, False, 0.95, 2026),
        ("SBI_TD_G7_ENROLLED", "Td: Grade 7 Enrolled Learners",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_TD_G7_MALE", "Td: Grade 7 Given Td Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_TD_G7_FEMALE", "Td: Grade 7 Given Td Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_TD_G7_TOTAL", "Td: Grade 7 Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("SBI_TD_G7_PCT", "Td: Grade 7 Percentage",
         "percentage", "annual", "percentage",
         100, "SBI_TD_G7_ENROLLED", True, False, 0.95, 2026),

        # --- File 10: G1 & G7 given MR vaccine (same shape as Td) ---
        ("SBI_MR_G1_ENROLLED", "MR: Grade 1 Enrolled Learners",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_MR_G1_MALE", "MR: Grade 1 Given MR Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_MR_G1_FEMALE", "MR: Grade 1 Given MR Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_MR_G1_TOTAL", "MR: Grade 1 Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("SBI_MR_G1_PCT", "MR: Grade 1 Percentage",
         "percentage", "annual", "percentage",
         100, "SBI_MR_G1_ENROLLED", True, False, 0.95, 2026),
        ("SBI_MR_G7_ENROLLED", "MR: Grade 7 Enrolled Learners",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_MR_G7_MALE", "MR: Grade 7 Given MR Male",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_MR_G7_FEMALE", "MR: Grade 7 Given MR Female",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("SBI_MR_G7_TOTAL", "MR: Grade 7 Total",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("SBI_MR_G7_PCT", "MR: Grade 7 Percentage",
         "percentage", "annual", "percentage",
         100, "SBI_MR_G7_ENROLLED", True, False, 0.95, 2026),

        # --- File 11: HPV (female-only; SBI + CBI delivery) ---
        ("HPV_G4_ENROLLED", "HPV: Grade 4 Female Enrolled (public + private)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("HPV1_SBI", "HPV1 via SBI (Grade 4 female, >=9 yrs)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("HPV1_SBI_PCT", "HPV1 SBI Percentage",
         "percentage", "annual", "percentage",
         100, "HPV_G4_ENROLLED", True, False, 0.95, 2026),
        ("HPV1_CBI", "HPV1 via CBI (9-year-old female)",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("HPV1_COMBINED", "HPV1 Combined Total (SBI + CBI)",
         "count", "annual", "sum", 100, None, True, False, None, None),
        ("HPV2_CBI", "HPV2 via CBI",
         "count", "annual", "count", 100, None, False, False, None, None),
        ("HPV2_PCT", "HPV2 Percentage (of HPV1 recipients)",
         "percentage", "annual", "percentage",
         100, "HPV1_COMBINED", True, False, 0.95, 2026),
    ],
}

# =====================================================
# SEED FUNCTION
# =====================================================

def seed_indicators():
    conn = psycopg2.connect(**DB_CONFIG)
    cur = conn.cursor()

    total_inserted = 0
    total_skipped = 0

    for program_code, indicators in INDICATORS.items():

        # Get program id
        cur.execute(
            "SELECT id FROM programs WHERE code = %s",
            (program_code,)
        )
        result = cur.fetchone()
        if not result:
            print(f"WARNING: Program '{program_code}' not found. Skipping.")
            continue
        program_id = result[0]

        for ind in indicators:
            (code, name, unit, frequency_type, formula_type,
             rate_multiplier, denominator_source, is_computed,
             is_sensitive, target_value, target_year) = ind

            # Check if already exists
            cur.execute(
                "SELECT id FROM indicators WHERE code = %s",
                (code,)
            )
            if cur.fetchone():
                print(f"  SKIP (exists): {code}")
                total_skipped += 1
                continue

            # Insert
            cur.execute("""
                INSERT INTO indicators (
                    program_id, code, name, unit, frequency_type,
                    formula_type, rate_multiplier, denominator_source,
                    is_computed, is_sensitive, target_value, target_year,
                    year_introduced
                ) VALUES (
                    %s, %s, %s, %s, %s,
                    %s, %s, %s,
                    %s, %s, %s, %s,
                    2026
                )
            """, (
                program_id, code, name, unit, frequency_type,
                formula_type, rate_multiplier, denominator_source,
                is_computed, is_sensitive, target_value, target_year
            ))
            print(f"  INSERTED: {code}")
            total_inserted += 1

    conn.commit()
    cur.close()
    conn.close()

    print(f"\nDone. Inserted: {total_inserted} | Skipped: {total_skipped}")


if __name__ == "__main__":
    seed_indicators()